=== bitctrl/de.bsvrz.sys.startstopp.console/startStoppOld/startStopp.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- Wurzelelement -->
<!ELEMENT konfiguration (startStopp)>

<!-- Definiert das jeweils ein versioniertes startStopp-Element -->
<!ELEMENT startStopp (global, applikationen?)>
<!ATTLIST startStopp
	Versionsnummer CDATA #REQUIRED
	ErstelltAm CDATA #REQUIRED
	ErstelltDurch CDATA #REQUIRED
	Aenderungsgrund CDATA #REQUIRED
>

<!-- Globaler Abschnitt, der für _alle_ eines startStopp-Elementes Applikationen gilt -->
<!ELEMENT global (makrodefinition*, kernsystem*, zugangdav, usv?,  rechner*, protokolldatei*)>

<!-- Definition des Kernsystems, das vor allen weiteren Anwendungen gestartet
 	 sein muss. Definition über Nennung der Applikationen in Startreihenfolge.
	 Optional: wartezeit (die Zeit die vor dem Start der Applikation gewartet wird in Sekunden).
   Optional: mitInkarnationsname (soll der Parameter -inkarnationsname= beim Aufruf der Inkarnation 
             hinzugefügt werden soll oder nicht (nicht alle Prozesse des Kernsystems kommen mit diesem 
             Parameter zurecht), Default: nein
-->
     
<!ELEMENT kernsystem EMPTY>
<!ATTLIST kernsystem
	inkarnationsname CDATA #REQUIRED
	wartezeit CDATA #IMPLIED 
	mitInkarnationsname ( ja | nein ) #IMPLIED 
>

<!-- Element usv mit PID -->
<!ELEMENT usv EMPTY>
<!ATTLIST usv
	pid CDATA #REQUIRED
>

<!-- Definition eines Textmakros, der unter Angabe des Definierten Namens im
	 applikationsspezifischen Teil referenziert werden kann. -->
<!ELEMENT makrodefinition EMPTY>
<!ATTLIST makrodefinition
	name CDATA #REQUIRED
	wert CDATA #REQUIRED
>

<!-- Benennung der Rechner im System -->
<!ELEMENT rechner EMPTY>
<!ATTLIST rechner
	name CDATA #REQUIRED
	tcpAdresse CDATA #REQUIRED
>


<!-- Definition Element zugangdav
		Die Attribute adresse und port entsprechen der Adresse und dem
		Port, unter dem der DaV erreichbar ist. Für die Verbindung sind
		die Attribute username und passwort unerlässlich.
		Wird auch für benutzt, wenn der DaV auf dem lokalen Rechener,
		IP=127.0.0.1, läuft.
		-->
<!ELEMENT zugangdav EMPTY>
<!ATTLIST zugangdav
	adresse CDATA #REQUIRED
	port CDATA #REQUIRED
	username CDATA #REQUIRED
	passwort CDATA #REQUIRED
>



<!-- Definition einer Protokolldatei -->
<!--	"groesse": MByte -->
<!ELEMENT protokolldatei EMPTY>
<!ATTLIST protokolldatei
	name CDATA #REQUIRED
      nameDatei CDATA #REQUIRED
	groesse CDATA #REQUIRED
>
<!-- Applikationsspezifischer Abschnitt -->
<!ELEMENT applikationen (inkarnation*)>

<!ELEMENT inkarnation (applikation, aufrufparameter*, startart?,
					   startbedingung*, stoppbedingung*, standardAusgabe?, standardFehlerAusgabe?,
					   startFehlerverhalten?, stoppFehlerverhalten?)>
<!-- Name dieser Inkarnation, der an anderer Stelle verwendet wird -->
<!ATTLIST inkarnation
	name CDATA #REQUIRED
>

<!-- Name der aufzurufenden Applikation (inkl. optionaler Pfadangabe) -->
<!ELEMENT applikation EMPTY>
<!ATTLIST applikation
	name CDATA #REQUIRED
>

<!-- Zeichenkette mit Aufrufparameter(n) -->
<!ELEMENT aufrufparameter EMPTY>
<!ATTLIST aufrufparameter
	wert CDATA #REQUIRED
>

<!-- "option" kann die Werte "automatisch", "manuell" und "intervall" haben.
	 "neustart" kann die Werte "ja" (Standard) und "nein" haben.
	 Bei "wert=intervall" kann über "intervall" der Startzeitpunkt der Applikation
	 spezifiziert werden. -->
<!ELEMENT startart EMPTY>
<!ATTLIST startart
	option ( automatisch | manuell | intervall ) "automatisch"
	neustart ( ja | nein ) "ja"
	intervall CDATA #IMPLIED
>

<!-- Festlegen der Startbedingungen, d. h. "vorgaenger", die bereits laufen
	 müssen. Die "warteart" gibt an, ob lediglich auf den "start" der
	 Applikation gewartet werden muss oder sogar auf die Beendigung der
	 "initialisierung". Optional: der Rechner und die Wartezeit. -->
<!ELEMENT startbedingung EMPTY>
<!ATTLIST startbedingung
	vorgaenger CDATA #REQUIRED
	warteart ( beginn | ende ) "beginn"
	rechner CDATA #IMPLIED
	wartezeit CDATA #IMPLIED
>

<!-- Festlegen der stoppbedingungen, d. h. "nachfolger", die bereits laufen
	 müssen, optional der Rechner und optionaler Wartezeit. -->
<!ELEMENT stoppbedingung EMPTY>
<!ATTLIST stoppbedingung
	nachfolger CDATA #REQUIRED
	rechner CDATA #IMPLIED
	wartezeit CDATA #IMPLIED
>

<!-- Umleitung der Standardausgabe.
	 "option" kann "ignorieren" (Standard), "eigeneDatei", oder "gemeinsam"
	 sein.
	 Bei "option={eigeneDatei|gemeinsam}" muss ein "dateiname" angegeben werden, welcher
	 einer der Protokolldateien aus dem globalen Abschnitt entspricht.
-->
<!ELEMENT standardAusgabe EMPTY>
<!ATTLIST standardAusgabe
	option ( ignorieren | eigene | gemeinsame ) "ignorieren"
	dateiname CDATA #IMPLIED
>

<!-- Umleitung der Standardfehlerausgabe.
	 "option" kann "ignorieren" (Standard), "eigeneDatei", oder "gemeinsam" sein.
	 Bei "option={eigeneDatei|gemeinsam}" muss ein "dateiname" angegeben werden, welcher
	 einer der Protokolldateien aus dem globalen Abschnitt entspricht.
-->
<!ELEMENT standardFehlerAusgabe EMPTY>
<!ATTLIST standardFehlerAusgabe
	option ( ignorieren | eigene | gemeinsame ) "ignorieren"
	dateiname CDATA #IMPLIED
>

<!-- Startverhalten bei Fehlern.
	 "option" kann "herunterfahren", "abbruch" oder "ignorieren" (Standard)
	 sein.
	 "wiederholungen" gibt an, wie oft der Startversuch wiederholt wird, bevor
	 das in "option" definierte Verhalten ausgeführt wird.
-->
<!ELEMENT startFehlerverhalten EMPTY>
<!ATTLIST startFehlerverhalten
	option ( beenden | abbruch | ignorieren ) "ignorieren"
	wiederholungen CDATA #IMPLIED
>

<!-- Stopverhalten bei Fehlern.
	 "option" kann "abbruch", "" (Standard) oder "ignorieren" sein.
	 "wiederholungen" gibt an, wie oft der Stopversuch wiederholt wird, bevor
	 das in "option" definierte Verhalten ausgeführt wird.
-->
<!ELEMENT stoppFehlerverhalten EMPTY>
<!ATTLIST stoppFehlerverhalten
	option ( stopp | abbruch | ignorieren ) "ignorieren"
	wiederholungen CDATA #IMPLIED
>

=== bitctrl/de.bsvrz.sys.startstopp.console/startStoppOld/startStoppBeispiel.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE konfiguration PUBLIC "-//startstopp//DTD Dokument//DE" "startStopp.dtd">

<konfiguration>
  <startStopp Versionsnummer="1" ErstelltAm="19.09.2008 11:57:42" ErstelltDurch="Lensing/Drapp" Aenderungsgrund="Konfiguration">
    <global>
      <makrodefinition name="host" wert="127.0.0.1" />
      <makrodefinition name="java" wert="C:/Programme/Java/jdk1.6.0_02/bin/java" />
      <makrodefinition name="root" wert="C:/kernsoftware-startstopp-r1" />
      <makrodefinition name="benutzer" wert="Tester" />
      <makrodefinition name="passwortdatei" wert="%root%/skripte-dosshell/passwd" />
      <makrodefinition name="authentifizierung" wert="-benutzer=%benutzer% -authentifizierung=%passwortdatei%" />
      <makrodefinition name="dav1Host" wert="localhost" />
      <makrodefinition name="dav1AppPort" wert="8083" />
      <makrodefinition name="dav1DavPort" wert="8082" />
      <makrodefinition name="debugDefaults" wert="-debugFilePath=%root%" />
      <makrodefinition name="dav1einstellungen" wert="-davAppPort=%dav1AppPort% -davDavPort=%dav1DavPort% %debugDefaults%" />
      <makrodefinition name="dav1" wert="-datenverteiler=%dav1Host%:%dav1AppPort% %authentifizierung% %debugDefaults%" />
      <makrodefinition name="dav1OhneAuthentifizierung" wert="-datenverteiler=%dav1Host%:%dav1AppPort% %debugDefaults%" />
      <kernsystem inkarnationsname="Datenverteiler" />
      <kernsystem inkarnationsname="Konfiguration" />
      <kernsystem inkarnationsname="Parametrierung" />
      <kernsystem inkarnationsname="Betriebsmeldungsverwaltung" />
      <zugangdav adresse="%host%" port="8083" username="Tester" passwort="geheim" />
      <usv pid="usv.testUSV" />
<!--
      <usv pid="usv.testUSV" />
      <rechner name="Rechner 1" tcpAdresse="192.0.1.96" />
-->
      <rechner name="Rechner 12" tcpAdresse="192.0.1.69" />

      <protokolldatei name="dav" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\dav.TXT" groesse="1" />
      <protokolldatei name="davfehler" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\dav.TXT" groesse="1" />
      <protokolldatei name="konf" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\konfiguration.log" groesse="1" />
      <protokolldatei name="konffehler" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\konfgurationFehler.log" groesse="1" />
      <protokolldatei name="gem" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\gemeinsameDatei.log" groesse="1" />
      <protokolldatei name="gemfehler" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\gemeinsameDateiFehler.log" groesse="1" />
      <protokolldatei name="USOut" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\USout.txt" groesse="1" />
      <protokolldatei name="USErr" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\USerr.txt" groesse="1" />
      <protokolldatei name="App1.1Out" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\app1_1_out.txt" groesse="1" />
      <protokolldatei name="App1.1Err" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\app1_1_err.txt" groesse="1" />
      <protokolldatei name="App1.2Out" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\app1_2_out.txt" groesse="1" />
      <protokolldatei name="App1.2Err" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\app1_2_err.txt" groesse="1" />
      <protokolldatei name="App1.3Out" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\app1_3_out.txt" groesse="1" />
      <protokolldatei name="App1.3Err" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\app1_3_err.txt" groesse="1" />
      <protokolldatei name="App1.4Out" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\app1_4_out.txt" groesse="1" />
      <protokolldatei name="App1.4Err" nameDatei="C:\kernsoftware-startstopp-r1\StartStopp\app1_4_err.txt" groesse="1" />
    </global>
    <applikationen>
      <inkarnation name="Datenverteiler">
        <applikation name="java -cp" />
        <aufrufparameter wert=" %root%/distributionspakete/de.bsvrz.dav.dav/de.bsvrz.dav.dav-runtime.jar" />
        <aufrufparameter wert=" -Xmx200m" />
        <aufrufparameter wert=" de.bsvrz.dav.dav.main.Transmitter" />
        <aufrufparameter wert=" %dav1einstellungen%" />
        <aufrufparameter wert=" -rechtePruefung=nein" />
        <aufrufparameter wert=" -debugLevelStdErrText=INFO" />
        <aufrufparameter wert=" -debugLevelFileText=CONFIG" />
        <startart option="automatisch" neustart="ja" intervall="" />
        <standardAusgabe option="ignorieren" dateiname="dav" />
        <standardFehlerAusgabe option="ignorieren" dateiname="davfehler" />
        <startFehlerverhalten option="ignorieren" wiederholungen="5" />
        <stoppFehlerverhalten option="ignorieren" wiederholungen="5" />
      </inkarnation>
      <inkarnation name="Konfiguration">
        <applikation name="java -cp" />
        <aufrufparameter wert=" %root%/distributionspakete/de.bsvrz.puk.config/de.bsvrz.puk.config-runtime.jar" />
        <aufrufparameter wert=" -Xmx300m" />
        <aufrufparameter wert=" de.bsvrz.puk.config.main.ConfigurationApp" />
        <aufrufparameter wert=" %dav1OhneAuthentifizierung%" />
        <aufrufparameter wert=" -benutzer=configuration" />
        <aufrufparameter wert=" -authentifizierung=%passwortdatei%" />
        <aufrufparameter wert=" -verwaltung=%root%/konfiguration/verwaltungsdaten.xml" />
        <aufrufparameter wert=" -benutzerverwaltung=%root%/konfiguration/benutzerverwaltung.xml" />
        <aufrufparameter wert=" -debugLevelStdErrText=INFO" />
        <aufrufparameter wert=" -debugLevelFileText=CONFIG" />
        <startart option="automatisch" neustart="ja" intervall="" />
        <standardAusgabe option="eigene" dateiname="konf" />
        <standardFehlerAusgabe option="eigene" dateiname="konffehler" />
        <startFehlerverhalten option="ignorieren" wiederholungen="5" />
        <stoppFehlerverhalten option="stopp" wiederholungen="1" />
      </inkarnation>
      <inkarnation name="Parametrierung">
        <applikation name="java -cp" />
        <aufrufparameter wert=" %root%/distributionspakete/de.kappich.puk.param/de.kappich.puk.param-runtime.jar" />
        <aufrufparameter wert=" de.kappich.puk.param.main.ParamApp" />
        <aufrufparameter wert=" %dav1%" />
        <aufrufparameter wert=" -sleep=200" />
        <aufrufparameter wert=" -parameterVerzeichnis=%root%/parameter_derby" />
        <aufrufparameter wert=" -debugLevelStdErrText=WARNING" />
        <aufrufparameter wert=" -debugLevelFileText=CONFIG" />
        <startart option="automatisch" neustart="ja" intervall="" />
        <standardAusgabe option="gemeinsame" dateiname="gem" />
        <standardFehlerAusgabe option="gemeinsame" dateiname="gemfehler" />
        <startFehlerverhalten option="ignorieren" wiederholungen="5" />
        <stoppFehlerverhalten option="ignorieren" wiederholungen="5" />
      </inkarnation>
      <inkarnation name="Betriebsmeldungsverwaltung">
        <applikation name="java -cp" />
        <aufrufparameter wert=" %root%/distributionspakete/de.kappich.vew.bmvew/de.kappich.vew.bmvew-runtime.jar" />
        <aufrufparameter wert=" de.kappich.vew.bmvew.main.SimpleMessageManager" />
        <aufrufparameter wert=" %dav1%" />
        <aufrufparameter wert=" -debugLevelStdErrText=WARNING" />
        <aufrufparameter wert=" -debugLevelFileText=CONFIG" />
        <startart option="automatisch" neustart="ja" intervall="" />
        <standardAusgabe option="gemeinsame" dateiname="gem" />
        <standardFehlerAusgabe option="gemeinsame" dateiname="gemfehler" />
        <startFehlerverhalten option="ignorieren" wiederholungen="5" />
        <stoppFehlerverhalten option="ignorieren" wiederholungen="5" />
      </inkarnation>
      <inkarnation name="Ueberpruefung System">
        <applikation name="java -cp" />
        <aufrufparameter wert=" %root%/distributionspakete/de.bsvrz.sys.testsys/de.bsvrz.sys.testsys.jar;%root%/distributionspakete/de.bsvrz.dav.dav/de.bsvrz.dav.dav-runtime.jar;%root%/distributionspakete/de.kappich.puk.param/de.kappich.puk.param-runtime.jar;%root%/distributionspakete/de.bsvrz.sys.funclib.application/de.bsvrz.sys.funclib.application.jar;%root%/distributionspakete/de.bsvrz.sys.funclib.operatingMessage/de.bsvrz.sys.funclib.operatingMessage.jar" />
        <aufrufparameter wert=" -Xmx200m" />
        <aufrufparameter wert=" de.bsvrz.sys.testsys.testsys.UeberpruefungSystemApp" />
        <aufrufparameter wert=" %dav1%" />
        <aufrufparameter wert=" -debugLevelStdErrText=INFO" />
        <aufrufparameter wert=" -debugLevelFileText=CONFIG" />
        <aufrufparameter wert=" -ueberpruefer=de.bsvrz.sys.testsys.modulUhrzeit.ModulUhrzeit" />
        <startart option="automatisch" neustart="nein" intervall="" />
        <standardAusgabe option="gemeinsame" dateiname="gem" />
        <standardFehlerAusgabe option="gemeinsame" dateiname="gemfehler" />
        <startFehlerverhalten option="ignorieren" wiederholungen="5" />
        <stoppFehlerverhalten option="ignorieren" wiederholungen="5" />
      </inkarnation>
      <inkarnation name="Applikation 1.1">
        <applikation name="java -cp" />
        <aufrufparameter wert=" %root%/distributionspakete/de.bsvrz.sys.test.startstopp/de.bsvrz.sys.test.startstopp.jar;%root%/distributionspakete/de.bsvrz.dav.dav/de.bsvrz.dav.dav-runtime.jar;%root%/distributionspakete/de.kappich.puk.param/de.kappich.puk.param-runtime.jar;%root%/distributionspakete/de.bsvrz.sys.funclib.application/de.bsvrz.sys.funclib.application.jar;%root%/distributionspakete/de.bsvrz.sys.funclib.operatingMessage/de.bsvrz.sys.funclib.operatingMessage.jar" />
        <aufrufparameter wert=" -Xmx200m" />
        <aufrufparameter wert=" de.bsvrz.sys.test.startstopp.TestApp" />
        <aufrufparameter wert=" %dav1%" />
        <aufrufparameter wert=" -debugLevelStdErrText=INFO" />
        <aufrufparameter wert=" -debugLevelFileText=CONFIG" />
        <startart option="manuell" neustart="nein" intervall="" />
<!--
